### ISSUE TITLE
Drop PHP 5.x supports

### ISSUE THREAD

**Issue by peter279k** [sinergi/token#1]
As title. Since the `php-7.0` has been released for about three years.

I think it's time to drop all `php-5.x` supports.

And it can also use the new features to generate random strings.

For example, we can use the `random_int` to generate the random numbers easily.

@gabrielbull, what do you think about this?

Once this issue is accepted, I can work on this :).

**Comment by gabrielbull** [comment]
@peter279k I've added you to the project, since I am no longer maintaining it. All yours.

**Comment by peter279k** [comment]
@gabrielbull, thanks for your reply. I will work on this.

**Comment by peter279k** [comment]
Closed via PR #1.
